#!/bin/bash
echo "Script started:"
a=10
b=35

echo "Before a = $a"
echo "Before b = $b"

a=$[ $a - $b ]
b=$[$b+$a]       # == b+(a-b) => a
a=$[$b - $a]     # == a-(a-b) => b

echo "After a = $a"
echo "After b = $b"

echo "The End!"
